### ISSUE TITLE
[MAJOR BUG] mcedit.ga is unavailable

### ISSUE THREAD

**Issue by hron84** [mcedit/mcedit.github.com#2]
I tried to follow a link from mcedit.net for mcedit 1.x downloads, but this link: http://khroki.github.io/MCEdit-Unified/ redirects me to mcedit.ga which is unavailable (confirmed by [IsUp.ME](http://isup.me/mcedit.ga)). Please take a look into it.

Note: this is a crosslinked issue with Khroki/MCEdit-Unified#669. Please, please work together on some solution, at least remove the misleading links and/or the broken redirection.

**Comment by codewarrior0** [comment]
Direct downloads: https://github.com/Khroki/MCEdit-Unified/releases

**Comment by codewarrior0** [comment]
Did what I could.

**Comment by hron84** [comment]
@codewarrior0 could you please update links then?

**Comment by Khroki** [comment]
This has been fixed, it may take a while for the DNS servers to reflect this change though.

**Comment by Khroki** [comment]
Also it is now fully hosted on github so it shouldn't realistically go down again.

**Comment by hron84** [comment]
Thanks
